apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-mock.fullname" . }}
  labels:
    {{- include "llm-mock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "llm-mock.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "llm-mock.name" . }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ include "llm-mock.fullname" . }}
      {{- end }}
      containers:
        - name: llm-mock
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
