{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "llm-mock.fullname" . }}
  labels:
    {{- include "llm-mock.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "llm-mock.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "llm-mock.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
